name = "saladsync-portfolio"
compatibility_date = "2024-01-01"

pages_build_output_dir = "./"

[site]
bucket = "./"

# Environment variables
[env.production]
name = "saladsync-portfolio"

[env.preview]
name = "saladsync-portfolio-preview"
